<a href="https://colab.research.google.com/github/ngcthanh2903/pytorch/blob/main/convolution_pytorch_low_level.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch 
from torch.nn import functional as F
import tensorflow as tf

In [ ]:
input = torch.randn(1,1,4,4, requires_grad=True)
print(input,input.shape)


tensor([[[[ 0.3416, -0.0833, -1.6076,  0.7049],
          [ 0.6684,  0.3296,  1.3179, -1.9981],
          [ 0.8011,  0.3040,  1.1764,  1.9984],
          [ 1.4194,  1.0368, -1.7810,  0.5352]]]], requires_grad=True) torch.Size([1, 1, 4, 4])


In [ ]:
weight = torch.randn(1,1,3,3, requires_grad=True)
print(weight,weight.shape)

tensor([[[[ 0.0386,  0.8483, -0.2089],
          [-0.9488, -0.7155,  0.9955],
          [ 0.1745, -0.3984,  0.6921]]]], requires_grad=True) torch.Size([1, 1, 3, 3])


In [ ]:
output = F.conv2d(input, weight)
output

tensor([[[[ 1.5532, -3.7914],
          [-1.1745,  3.6681]]]], grad_fn=<ConvolutionBackward0>)

In [ ]:
o = torch.conv2d(input,weight)
o

tensor([[[[ 1.5532, -3.7914],
          [-1.1745,  3.6681]]]], grad_fn=<ConvolutionBackward0>)

In [ ]:
grad_output = torch.randn(output.shape)

In [ ]:
grad_weight = torch.autograd.grad(output, weight, grad_output)
grad_weight

(tensor([[[[-1.7610,  0.8803,  3.0838],
           [ 3.2088,  2.6957,  2.5903],
           [-4.5069, -2.7738, -1.1588]]]]),)

In [ ]:
def tuple_of_tensors_to_tensor(tuple_of_tensors):
    return  torch.stack(list(tuple_of_tensors), dim=0)
tuple_of_tensors_to_tensor(grad_weight)   

tensor([[[[[-1.7610,  0.8803,  3.0838],
           [ 3.2088,  2.6957,  2.5903],
           [-4.5069, -2.7738, -1.1588]]]]])

In [ ]:
w_grad = torch.conv2d(input,grad_output)
w_grad

tensor([[[[ 0.4919,  2.2467, -2.2996],
          [ 0.3366,  2.2948,  2.6694],
          [ 1.7194, -3.1001,  0.3153]]]], grad_fn=<ConvolutionBackward0>)

In [ ]:
grad_w = F.grad.conv2d_weight(input, weight.shape, grad_output)
grad_w

tensor([[[[ 0.4919,  2.2467, -2.2996],
          [ 0.3366,  2.2948,  2.6694],
          [ 1.7194, -3.1001,  0.3153]]]],
       grad_fn=<ConvolutionBackwardBackward0>)

In [ ]:
o = torch.tensor(o)
o

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


tensor([[[[ 1.6660, -2.9301],
          [-0.3271,  0.1683]]]])

In [ ]:
 torch.nn.grad.conv2d_weight(input, weight.shape, grad_output)

tensor([[[[ 0.4919,  2.2467, -2.2996],
          [ 0.3366,  2.2948,  2.6694],
          [ 1.7194, -3.1001,  0.3153]]]],
       grad_fn=<ConvolutionBackwardBackward0>)

In [ ]:
grad_in = torch.autograd.grad(output, input, grad_output)
grad_in

(tensor([[[[-0.0252, -0.5470,  0.3067, -0.0419],
           [ 0.6272,  0.4990,  0.7499, -0.1898],
           [-0.2812, -1.5989, -1.6909,  1.9942],
           [ 0.0307,  0.2551, -0.6207,  1.2901]]]]),)

In [ ]:
in_grad = F.grad.conv2d_input(input.shape, weight, grad_output)
in_grad

tensor([[[[-0.0252, -0.5470,  0.3067, -0.0419],
          [ 0.6272,  0.4990,  0.7499, -0.1898],
          [-0.2812, -1.5989, -1.6909,  1.9942],
          [ 0.0307,  0.2551, -0.6207,  1.2901]]]],
       grad_fn=<ConvolutionBackwardBackward0>)

In [ ]:
x = torch.arange(16).view(1, 1, 4,4)
x

tensor([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15]]]])

In [ ]:
torch.flip(x, [2,3])

tensor([[[[15, 14, 13, 12],
          [11, 10,  9,  8],
          [ 7,  6,  5,  4],
          [ 3,  2,  1,  0]]]])

In [ ]:
input.shape

torch.Size([1, 1, 3, 3])

In [ ]:
grad_in=torch.conv_transpose2d(grad_output, weight)
grad_in.shape

torch.Size([1, 1, 4, 4])

In [ ]:
input

tensor([[[[ 0.3416, -0.0833, -1.6076,  0.7049],
          [ 0.6684,  0.3296,  1.3179, -1.9981],
          [ 0.8011,  0.3040,  1.1764,  1.9984],
          [ 1.4194,  1.0368, -1.7810,  0.5352]]]], requires_grad=True)

In [ ]:
torch.flip(input, [2,3]).shape
weight

tensor([[[[-0.5158, -0.9293, -0.6043],
          [-0.0041,  0.8445,  0.0466],
          [ 0.9831, -1.1239,  0.0546]]]], requires_grad=True)

In [ ]:
torch.flip(weight, [2,3])

tensor([[[[ 0.6921, -0.3984,  0.1745],
          [ 0.9955, -0.7155, -0.9488],
          [-0.2089,  0.8483,  0.0386]]]], grad_fn=<FlipBackward0>)

In [ ]:
grad_output.shape
input.shape

torch.Size([1, 1, 4, 4])

In [ ]:
x
paddings = (1,5,3,3,0,0)
torch.nn.functional.pad(grad_output,paddings).shape


torch.Size([1, 1, 8, 8])

In [ ]:
grad_input = torch.conv2d(torch.nn.functional.pad(grad_output,paddings),torch.flip(weight,[2,3]))
grad_input.shape
print(grad_input)

tensor([[[[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
          [-0.5470,  0.3067, -0.0419,  0.0000,  0.0000,  0.0000],
          [ 0.4990,  0.7499, -0.1898,  0.0000,  0.0000,  0.0000],
          [-1.5989, -1.6909,  1.9942,  0.0000,  0.0000,  0.0000],
          [ 0.2551, -0.6207,  1.2901,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]]]],
       grad_fn=<ConvolutionBackward0>)


In [ ]:
import torch 
from torch.nn import functional as F
import tensorflow as tf

In [ ]:
input = torch.randn(1,1,4,4, requires_grad=True)
print(input,input.shape)


tensor([[[[-0.2921,  0.7333, -0.3372, -0.6393],
          [-1.3351, -0.4130,  0.1204,  0.1441],
          [-0.1641,  0.5014, -0.1830,  1.0376],
          [-1.7541,  1.7945,  0.2673, -0.7757]]]], requires_grad=True) torch.Size([1, 1, 4, 4])


In [ ]:
weight = torch.randn(1,1,3,3, requires_grad=True)
print(weight,weight.shape)

tensor([[[[-2.4179, -0.1159,  0.3991],
          [ 0.3739, -1.3596, -0.8309],
          [ 0.0058,  0.2456, -1.0247]]]], requires_grad=True) torch.Size([1, 1, 3, 3])


In [ ]:
output = F.conv2d(input, weight)
output

tensor([[[[ 0.7586, -3.5322],
          [ 2.8896,  1.4871]]]], grad_fn=<ConvolutionBackward0>)

In [ ]:
grad_output = torch.randn(output.shape)

In [ ]:
grad_w = F.grad.conv2d_weight(input, weight.shape, grad_output)
grad_w

tensor([[[[ 1.5239, -0.8220, -0.2243],
          [ 0.6254,  0.4231, -0.8387],
          [-0.4429, -1.4416,  1.3269]]]],
       grad_fn=<ConvolutionBackwardBackward0>)

In [ ]:
in_grad = F.grad.conv2d_input(input.shape, weight, grad_output)
in_grad

tensor([[[[ 2.2249e+00, -1.2897e+00, -4.3420e-01,  2.3050e-01],
          [ 5.2961e-01,  3.5534e+00, -6.6779e-02, -8.1735e-01],
          [-1.4043e-01, -4.7532e-02,  2.5346e+00,  1.1081e-01],
          [-2.0805e-03, -9.3605e-02,  1.6266e-01,  8.6646e-01]]]],
       grad_fn=<ConvolutionBackwardBackward0>)

In [ ]:
import torch 
print(torch.nn.grad.conv2d_weight(input, weight.shape, grad_output))

tensor([[[[ 1.5239, -0.8220, -0.2243],
          [ 0.6254,  0.4231, -0.8387],
          [-0.4429, -1.4416,  1.3269]]]],
       grad_fn=<ConvolutionBackwardBackward0>)


In [ ]:
print(F.conv2d(input,grad_output))

tensor([[[[ 1.5239, -0.8220, -0.2243],
          [ 0.6254,  0.4231, -0.8387],
          [-0.4429, -1.4416,  1.3269]]]], grad_fn=<ConvolutionBackward0>)


In [ ]:
print(F.conv_transpose2d(weight,grad_output))

tensor([[[[ 2.2249e+00, -1.2897e+00, -4.3420e-01,  2.3050e-01],
          [ 5.2961e-01,  3.5534e+00, -6.6779e-02, -8.1735e-01],
          [-1.4043e-01, -4.7532e-02,  2.5346e+00,  1.1081e-01],
          [-2.0805e-03, -9.3605e-02,  1.6266e-01,  8.6646e-01]]]],
       grad_fn=<ConvolutionBackward0>)


In [ ]:
print(grad_output)
#print(grad_output.transpose(0,1))
print(torch.flip(grad_output, [2,3]))

tensor([[[[-0.0268, -0.5786],
          [-0.1461,  0.5015]]]])
tensor([[[[ 0.5015, -0.1461],
          [-0.5786, -0.0268]]]])


In [ ]:
print(F.conv2d(grad_output,torch.flip(weight, [2,3]),padding=2))

tensor([[[[ 2.2249e+00, -1.2897e+00, -4.3420e-01,  2.3050e-01],
          [ 5.2961e-01,  3.5534e+00, -6.6779e-02, -8.1735e-01],
          [-1.4043e-01, -4.7532e-02,  2.5346e+00,  1.1081e-01],
          [-2.0805e-03, -9.3605e-02,  1.6266e-01,  8.6646e-01]]]],
       grad_fn=<ConvolutionBackward0>)


In [ ]:
F.conv2d(grad_output,weight,padding=2)

tensor([[[[ 0.9430, -0.8178,  0.1365,  0.0033],
          [ 1.1349,  1.5489, -1.3390,  0.2111],
          [-0.0670,  1.5310,  3.1725, -1.7125],
          [-0.1442, -0.2956,  0.9717,  2.0444]]]],
       grad_fn=<ConvolutionBackward0>)

In [ ]:
di = torch.autograd.grad(output, weight, grad_output)

In [ ]:
dw=torch.autograd.grad(output, input, grad_output)

RuntimeError: ignored

In [ ]:
di

(tensor([[[[ 1.5239, -0.8220, -0.2243],
           [ 0.6254,  0.4231, -0.8387],
           [-0.4429, -1.4416,  1.3269]]]]),)

In [1]:
import torch 
from torch.nn import functional as F
input = torch.randn(3,3,4,4, requires_grad=True)
print(input,input.shape)
weight = torch.randn(3,3,3,3, requires_grad=True)
print(weight,weight.shape)
output = F.conv2d(input, weight)
print(output)

tensor([[[[ 5.5614e-01, -1.8750e+00,  2.0075e+00, -2.9357e-01],
          [-9.2188e-01, -3.4801e-01, -4.7713e-01, -7.1449e-01],
          [ 1.9278e-01, -1.1121e+00, -2.1745e-01, -1.4266e-01],
          [ 1.1392e+00,  1.4085e+00, -2.8118e-01, -5.8390e-01]],

         [[-3.3107e-01, -4.4286e-01,  7.2854e-01, -4.5434e-01],
          [ 2.2107e-01, -2.1869e+00, -1.0953e+00,  1.1792e+00],
          [ 4.4409e-01, -6.9943e-02, -3.2790e-01, -2.8303e+00],
          [-1.7804e-01,  1.3952e+00,  9.9036e-01,  9.5271e-01]],

         [[-4.5390e-01,  8.2875e-01, -2.3495e-01, -1.6899e+00],
          [ 3.8890e-02,  4.0726e-01,  7.1055e-01,  2.2195e+00],
          [ 1.9461e+00, -2.4010e-01, -2.7275e-01,  2.1861e-01],
          [-4.1627e-01,  2.7369e-01, -1.0602e+00,  7.9578e-01]]],


        [[[-6.5939e-01, -4.5104e-01, -4.4962e-01,  6.4025e-01],
          [ 1.4405e+00, -1.1731e+00, -2.0039e+00,  5.8011e-01],
          [-4.9149e-01, -5.1228e-02,  8.0398e-01, -6.7703e-01],
          [-3.6323e-01, -1.3562e

In [2]:
grad_output = torch.randn(output.shape)
grad_output

tensor([[[[-2.0247,  0.8940],
          [-0.3117,  1.6724]],

         [[ 0.7405,  0.4651],
          [ 0.0259,  0.4646]],

         [[ 1.0282, -1.1207],
          [-1.5272,  0.6078]]],


        [[[-0.6057, -0.5503],
          [-1.9377,  0.9763]],

         [[-0.6207, -0.2362],
          [ 0.6805,  0.1389]],

         [[-1.1634, -1.6919],
          [-1.2178,  1.4346]]],


        [[[-0.0476, -0.7858],
          [ 1.5846,  0.9308]],

         [[-1.1219, -1.2434],
          [-0.3038, -0.2611]],

         [[-0.1653, -0.6936],
          [ 0.1630,  0.4050]]]])

In [3]:
grad_w = F.grad.conv2d_weight(input, weight.shape, grad_output)
grad_w

tensor([[[[-5.9328,  4.1822, -1.4700],
          [-2.2954,  0.8827, -3.7725],
          [ 0.9865,  7.7072, -3.9711]],

         [[-2.7899,  3.3083, -1.2247],
          [-3.8608,  2.9392, -2.5223],
          [ 1.3178, -2.4826, -0.8067]],

         [[ 5.5958,  3.4250, -1.5529],
          [ 4.7280, -0.6415,  5.2962],
          [ 1.1928,  3.8693, -0.3447]]],


        [[[-0.7071, -2.6934,  1.2200],
          [-2.1859,  2.2324,  3.1365],
          [ 2.5860,  0.3557,  3.8660]],

         [[ 0.2579, -1.8230,  2.0535],
          [ 0.4604, -3.8581, -2.9891],
          [-0.0738, -1.0471, -3.4793]],

         [[ 0.8386, -1.1712, -5.1930],
          [-3.1600, -2.3447, -2.1012],
          [-0.6282, -3.8091, -0.4531]]],


        [[[ 1.3195, -4.8095,  5.7562],
          [-1.0337,  7.3774, -0.0807],
          [ 0.8166,  0.7490, -0.6679]],

         [[-2.2665,  5.3843,  4.5249],
          [ 1.9703, -3.2319, -7.5639],
          [-0.5504, -5.1465,  1.8261]],

         [[ 0.8664,  0.8488, -4.9858],
     

In [4]:
in_grad = F.grad.conv2d_input(input.shape, weight, grad_output)
in_grad

tensor([[[[-1.2485e+00,  2.6222e+00,  3.2269e+00, -1.7331e+00],
          [ 4.2159e+00, -3.2387e+00, -4.8671e+00,  7.5833e-01],
          [ 5.4669e-01,  5.9680e-01, -1.8771e+00,  1.8644e+00],
          [ 1.1582e-01, -2.7850e+00,  1.7557e+00, -2.1031e+00]],

         [[-8.5608e-01, -7.7094e+00,  2.6984e+00,  2.9519e+00],
          [-2.0414e+00,  9.9793e+00,  6.1334e+00, -8.1205e-01],
          [ 6.5971e+00,  1.3366e+00, -1.9847e+00, -3.7552e+00],
          [ 2.8936e+00, -4.4432e+00, -3.5181e+00, -6.2018e-01]],

         [[ 2.6343e-01, -2.6027e+00,  6.9093e+00, -2.5412e+00],
          [ 4.7629e-01,  1.2878e-01,  2.1352e+00, -2.3844e+00],
          [-4.5750e+00,  7.3614e-01,  8.1915e-01, -3.9185e+00],
          [ 3.2605e+00,  6.0741e-01,  2.0167e+00,  8.9596e-01]]],


        [[[ 1.3161e+00,  2.3870e+00, -1.7603e+00, -2.1441e+00],
          [ 1.1729e+00,  3.5941e-01,  2.8953e+00,  1.9508e+00],
          [ 2.3573e+00,  7.7918e-01, -1.4922e+00,  2.8853e+00],
          [ 7.3011e-01, -1.4113e

In [5]:

def convolution_backward(grad_out, X, weight):
    grad_weight = F.conv2d(X.transpose(0, 1), grad_out.transpose(0, 1)).transpose(0, 1)
    grad_X = F.conv_transpose2d(grad_out, weight)
    print('grad_w',grad_weight)
    print('grad_input',grad_X)
    #return grad_X, grad_weight
convolution_backward(grad_output,input,weight)    

grad_w tensor([[[[-5.9328,  4.1822, -1.4700],
          [-2.2954,  0.8827, -3.7725],
          [ 0.9865,  7.7072, -3.9711]],

         [[-2.7899,  3.3083, -1.2247],
          [-3.8608,  2.9392, -2.5223],
          [ 1.3178, -2.4826, -0.8067]],

         [[ 5.5958,  3.4250, -1.5529],
          [ 4.7280, -0.6415,  5.2962],
          [ 1.1928,  3.8693, -0.3447]]],


        [[[-0.7071, -2.6934,  1.2200],
          [-2.1859,  2.2324,  3.1365],
          [ 2.5860,  0.3557,  3.8660]],

         [[ 0.2579, -1.8230,  2.0535],
          [ 0.4604, -3.8581, -2.9891],
          [-0.0738, -1.0471, -3.4793]],

         [[ 0.8386, -1.1712, -5.1930],
          [-3.1600, -2.3447, -2.1012],
          [-0.6282, -3.8091, -0.4531]]],


        [[[ 1.3195, -4.8095,  5.7562],
          [-1.0337,  7.3774, -0.0807],
          [ 0.8166,  0.7490, -0.6679]],

         [[-2.2665,  5.3843,  4.5248],
          [ 1.9703, -3.2319, -7.5639],
          [-0.5504, -5.1465,  1.8261]],

         [[ 0.8664,  0.8488, -4.9858]

In [6]:
F.conv2d(grad_output,torch.flip(weight, [2,3]),padding=2)

tensor([[[[ 0.4669,  4.9409,  0.2809,  0.5156],
          [ 2.1236, -1.5404, -2.3685, -0.9711],
          [ 1.2982, -4.2700, -0.0250, -1.7186],
          [-2.4961, -4.9070, -1.3571, -0.9201]],

         [[-0.3664,  3.1676, -4.8623,  1.7783],
          [ 0.3252,  1.0790, -0.1622,  2.4773],
          [ 4.5315, -0.5061, -5.0010,  0.2615],
          [-2.3100,  0.4395,  0.4736, -0.8398]],

         [[ 3.2888, -4.2863, -2.2177, -1.2344],
          [-0.3471,  2.8637, -4.8309,  1.1789],
          [-3.5243,  1.5270,  2.7779, -4.3946],
          [ 3.7054, -3.1430,  0.3889, -2.1913]]],


        [[[-0.3768, -1.8162,  0.0558,  2.3566],
          [ 1.8392,  2.8887,  5.3843, -0.6919],
          [ 3.0175, -5.8256, -3.6912, -1.9147],
          [-3.2145, -1.1129,  3.0901,  0.2474]],

         [[ 0.5978, -0.7029, -4.0926, -0.9075],
          [ 0.4995, -3.9749,  1.1666,  3.4728],
          [-2.5649,  1.3587,  5.8098,  1.7257],
          [ 0.4260,  2.5561, -0.6090, -2.7558]],

         [[-0.2183,  3.2343,