<a href="https://colab.research.google.com/github/ngcthanh2903/pytorch/blob/main/convolution_pytorch_low_level.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch 
from torch.nn import functional as F
import tensorflow as tf

In [2]:
input = torch.randn(1,1,4,4, requires_grad=True)
print(input,input.shape)


tensor([[[[ 0.3416, -0.0833, -1.6076,  0.7049],
          [ 0.6684,  0.3296,  1.3179, -1.9981],
          [ 0.8011,  0.3040,  1.1764,  1.9984],
          [ 1.4194,  1.0368, -1.7810,  0.5352]]]], requires_grad=True) torch.Size([1, 1, 4, 4])


In [3]:
weight = torch.randn(1,1,3,3, requires_grad=True)
print(weight,weight.shape)

tensor([[[[ 0.0386,  0.8483, -0.2089],
          [-0.9488, -0.7155,  0.9955],
          [ 0.1745, -0.3984,  0.6921]]]], requires_grad=True) torch.Size([1, 1, 3, 3])


In [4]:
output = F.conv2d(input, weight)
output

tensor([[[[ 1.5532, -3.7914],
          [-1.1745,  3.6681]]]], grad_fn=<ConvolutionBackward0>)

In [5]:
o = torch.conv2d(input,weight)
o

tensor([[[[ 1.5532, -3.7914],
          [-1.1745,  3.6681]]]], grad_fn=<ConvolutionBackward0>)

In [6]:
grad_output = torch.randn(output.shape)

In [ ]:
grad_weight = torch.autograd.grad(output, weight, grad_output)
grad_weight

(tensor([[[[-1.7610,  0.8803,  3.0838],
           [ 3.2088,  2.6957,  2.5903],
           [-4.5069, -2.7738, -1.1588]]]]),)

In [ ]:
def tuple_of_tensors_to_tensor(tuple_of_tensors):
    return  torch.stack(list(tuple_of_tensors), dim=0)
tuple_of_tensors_to_tensor(grad_weight)   

tensor([[[[[-1.7610,  0.8803,  3.0838],
           [ 3.2088,  2.6957,  2.5903],
           [-4.5069, -2.7738, -1.1588]]]]])

In [7]:
w_grad = torch.conv2d(input,grad_output)
w_grad

tensor([[[[ 0.4919,  2.2467, -2.2996],
          [ 0.3366,  2.2948,  2.6694],
          [ 1.7194, -3.1001,  0.3153]]]], grad_fn=<ConvolutionBackward0>)

In [8]:
grad_w = F.grad.conv2d_weight(input, weight.shape, grad_output)
grad_w

tensor([[[[ 0.4919,  2.2467, -2.2996],
          [ 0.3366,  2.2948,  2.6694],
          [ 1.7194, -3.1001,  0.3153]]]],
       grad_fn=<ConvolutionBackwardBackward0>)

In [ ]:
o = torch.tensor(o)
o

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


tensor([[[[ 1.6660, -2.9301],
          [-0.3271,  0.1683]]]])

In [9]:
 torch.nn.grad.conv2d_weight(input, weight.shape, grad_output)

tensor([[[[ 0.4919,  2.2467, -2.2996],
          [ 0.3366,  2.2948,  2.6694],
          [ 1.7194, -3.1001,  0.3153]]]],
       grad_fn=<ConvolutionBackwardBackward0>)

In [10]:
grad_in = torch.autograd.grad(output, input, grad_output)
grad_in

(tensor([[[[-0.0252, -0.5470,  0.3067, -0.0419],
           [ 0.6272,  0.4990,  0.7499, -0.1898],
           [-0.2812, -1.5989, -1.6909,  1.9942],
           [ 0.0307,  0.2551, -0.6207,  1.2901]]]]),)

In [11]:
in_grad = F.grad.conv2d_input(input.shape, weight, grad_output)
in_grad

tensor([[[[-0.0252, -0.5470,  0.3067, -0.0419],
          [ 0.6272,  0.4990,  0.7499, -0.1898],
          [-0.2812, -1.5989, -1.6909,  1.9942],
          [ 0.0307,  0.2551, -0.6207,  1.2901]]]],
       grad_fn=<ConvolutionBackwardBackward0>)

In [15]:
x = torch.arange(16).view(1, 1, 4,4)
x

tensor([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15]]]])

In [16]:
torch.flip(x, [2,3])

tensor([[[[15, 14, 13, 12],
          [11, 10,  9,  8],
          [ 7,  6,  5,  4],
          [ 3,  2,  1,  0]]]])

In [ ]:
input.shape

torch.Size([1, 1, 3, 3])

In [13]:
grad_in=torch.conv_transpose2d(grad_output, weight)
grad_in.shape

torch.Size([1, 1, 4, 4])

In [17]:
input

tensor([[[[ 0.3416, -0.0833, -1.6076,  0.7049],
          [ 0.6684,  0.3296,  1.3179, -1.9981],
          [ 0.8011,  0.3040,  1.1764,  1.9984],
          [ 1.4194,  1.0368, -1.7810,  0.5352]]]], requires_grad=True)

In [ ]:
torch.flip(input, [2,3]).shape
weight

tensor([[[[-0.5158, -0.9293, -0.6043],
          [-0.0041,  0.8445,  0.0466],
          [ 0.9831, -1.1239,  0.0546]]]], requires_grad=True)

In [18]:
torch.flip(weight, [2,3])

tensor([[[[ 0.6921, -0.3984,  0.1745],
          [ 0.9955, -0.7155, -0.9488],
          [-0.2089,  0.8483,  0.0386]]]], grad_fn=<FlipBackward0>)

In [19]:
grad_output.shape
input.shape

torch.Size([1, 1, 4, 4])

In [20]:
x
paddings = (1,5,3,3,0,0)
torch.nn.functional.pad(grad_output,paddings).shape


torch.Size([1, 1, 8, 8])

In [21]:
grad_input = torch.conv2d(torch.nn.functional.pad(grad_output,paddings),torch.flip(weight,[2,3]))
grad_input.shape
print(grad_input)

tensor([[[[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
          [-0.5470,  0.3067, -0.0419,  0.0000,  0.0000,  0.0000],
          [ 0.4990,  0.7499, -0.1898,  0.0000,  0.0000,  0.0000],
          [-1.5989, -1.6909,  1.9942,  0.0000,  0.0000,  0.0000],
          [ 0.2551, -0.6207,  1.2901,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]]]],
       grad_fn=<ConvolutionBackward0>)


In [22]:
import torch 
from torch.nn import functional as F
import tensorflow as tf

In [23]:
input = torch.randn(1,1,4,4, requires_grad=True)
print(input,input.shape)


tensor([[[[-0.2921,  0.7333, -0.3372, -0.6393],
          [-1.3351, -0.4130,  0.1204,  0.1441],
          [-0.1641,  0.5014, -0.1830,  1.0376],
          [-1.7541,  1.7945,  0.2673, -0.7757]]]], requires_grad=True) torch.Size([1, 1, 4, 4])


In [24]:
weight = torch.randn(1,1,3,3, requires_grad=True)
print(weight,weight.shape)

tensor([[[[-2.4179, -0.1159,  0.3991],
          [ 0.3739, -1.3596, -0.8309],
          [ 0.0058,  0.2456, -1.0247]]]], requires_grad=True) torch.Size([1, 1, 3, 3])


In [25]:
output = F.conv2d(input, weight)
output

tensor([[[[ 0.7586, -3.5322],
          [ 2.8896,  1.4871]]]], grad_fn=<ConvolutionBackward0>)

In [26]:
grad_output = torch.randn(output.shape)

In [27]:
grad_w = F.grad.conv2d_weight(input, weight.shape, grad_output)
grad_w

tensor([[[[ 1.5239, -0.8220, -0.2243],
          [ 0.6254,  0.4231, -0.8387],
          [-0.4429, -1.4416,  1.3269]]]],
       grad_fn=<ConvolutionBackwardBackward0>)

In [28]:
in_grad = F.grad.conv2d_input(input.shape, weight, grad_output)
in_grad

tensor([[[[ 2.2249e+00, -1.2897e+00, -4.3420e-01,  2.3050e-01],
          [ 5.2961e-01,  3.5534e+00, -6.6779e-02, -8.1735e-01],
          [-1.4043e-01, -4.7532e-02,  2.5346e+00,  1.1081e-01],
          [-2.0805e-03, -9.3605e-02,  1.6266e-01,  8.6646e-01]]]],
       grad_fn=<ConvolutionBackwardBackward0>)

In [29]:
import torch 
print(torch.nn.grad.conv2d_weight(input, weight.shape, grad_output))

tensor([[[[ 1.5239, -0.8220, -0.2243],
          [ 0.6254,  0.4231, -0.8387],
          [-0.4429, -1.4416,  1.3269]]]],
       grad_fn=<ConvolutionBackwardBackward0>)


In [30]:
print(F.conv2d(input,grad_output))

tensor([[[[ 1.5239, -0.8220, -0.2243],
          [ 0.6254,  0.4231, -0.8387],
          [-0.4429, -1.4416,  1.3269]]]], grad_fn=<ConvolutionBackward0>)


In [31]:
print(F.conv_transpose2d(weight,grad_output))

tensor([[[[ 2.2249e+00, -1.2897e+00, -4.3420e-01,  2.3050e-01],
          [ 5.2961e-01,  3.5534e+00, -6.6779e-02, -8.1735e-01],
          [-1.4043e-01, -4.7532e-02,  2.5346e+00,  1.1081e-01],
          [-2.0805e-03, -9.3605e-02,  1.6266e-01,  8.6646e-01]]]],
       grad_fn=<ConvolutionBackward0>)


In [ ]:
print(grad_output)
#print(grad_output.transpose(0,1))
print(torch.flip(grad_output, [2,3]))

tensor([[[[-0.0268, -0.5786],
          [-0.1461,  0.5015]]]])
tensor([[[[ 0.5015, -0.1461],
          [-0.5786, -0.0268]]]])


In [32]:
print(F.conv2d(grad_output,torch.flip(weight, [2,3]),padding=2))

tensor([[[[ 2.2249e+00, -1.2897e+00, -4.3420e-01,  2.3050e-01],
          [ 5.2961e-01,  3.5534e+00, -6.6779e-02, -8.1735e-01],
          [-1.4043e-01, -4.7532e-02,  2.5346e+00,  1.1081e-01],
          [-2.0805e-03, -9.3605e-02,  1.6266e-01,  8.6646e-01]]]],
       grad_fn=<ConvolutionBackward0>)


In [34]:
F.conv2d(grad_output,weight,padding=2)

tensor([[[[ 0.9430, -0.8178,  0.1365,  0.0033],
          [ 1.1349,  1.5489, -1.3390,  0.2111],
          [-0.0670,  1.5310,  3.1725, -1.7125],
          [-0.1442, -0.2956,  0.9717,  2.0444]]]],
       grad_fn=<ConvolutionBackward0>)

In [35]:
di = torch.autograd.grad(output, weight, grad_output)

In [37]:
dw=torch.autograd.grad(output, input, grad_output)

RuntimeError: ignored

In [36]:
di

(tensor([[[[ 1.5239, -0.8220, -0.2243],
           [ 0.6254,  0.4231, -0.8387],
           [-0.4429, -1.4416,  1.3269]]]]),)

In [ ]:
import torch 
from torch.nn import functional as F
input = torch.randn(1,1,4,4, requires_grad=True)
print(input,input.shape)
weight = torch.randn(1,1,3,3, requires_grad=True)
print(weight,weight.shape)
output = F.conv2d(input, weight)
print(output)

tensor([[[[-0.1117,  1.5516, -0.2136, -1.3680],
          [-0.8436,  0.8115, -1.6640, -0.7155],
          [ 0.9227, -1.2610, -1.9740,  0.2900],
          [-0.1510, -0.8380,  2.1046, -1.1020]]]], requires_grad=True) torch.Size([1, 1, 4, 4])
tensor([[[[-0.3951,  0.3634, -0.7430],
          [-1.3952, -1.1031,  0.7965],
          [ 0.2341,  0.1852, -1.7492]]]], requires_grad=True) torch.Size([1, 1, 3, 3])
tensor([[[[ 3.1585, -0.7087],
          [-3.4759,  5.8955]]]], grad_fn=<ConvolutionBackward0>)


In [ ]:
grad_output = torch.randn(output.shape)
grad_output

tensor([[[[ 1.5779, -0.1551],
          [-0.7963, -0.5219]]]])

In [ ]:
grad_w = F.grad.conv2d_weight(input, weight.shape, grad_output)
grad_w

tensor([[[[-0.1686,  2.7037,  1.5737],
          [-1.5337,  3.5730, -1.0941],
          [ 2.2092, -2.1147, -4.2606]]]], grad_fn=<SliceBackward0>)

In [ ]:
in_grad = F.grad.conv2d_input(input.shape, weight, grad_output)
in_grad

tensor([[[[-0.6235,  0.6347, -1.2288,  0.1152],
          [-1.8869, -1.6074,  1.8300,  0.2643],
          [ 1.4804,  1.8625, -2.8474, -0.1444],
          [-0.1864, -0.2696,  1.2963,  0.9129]]]],
       grad_fn=<ConvolutionBackward0>)

In [33]:

def convolution_backward(grad_out, X, weight):
    grad_weight = F.conv2d(X.transpose(0, 1), grad_out.transpose(0, 1)).transpose(0, 1)
    grad_X = F.conv_transpose2d(grad_out, weight)
    print('grad_w',grad_weight)
    print('grad_input',grad_X)
    #return grad_X, grad_weight
convolution_backward(grad_output,input,weight)    

grad_w tensor([[[[ 1.5239, -0.8220, -0.2243],
          [ 0.6254,  0.4231, -0.8387],
          [-0.4429, -1.4416,  1.3269]]]], grad_fn=<TransposeBackward0>)
grad_input tensor([[[[ 2.2249e+00, -1.2897e+00, -4.3420e-01,  2.3050e-01],
          [ 5.2961e-01,  3.5534e+00, -6.6779e-02, -8.1735e-01],
          [-1.4043e-01, -4.7532e-02,  2.5346e+00,  1.1081e-01],
          [-2.0805e-03, -9.3605e-02,  1.6266e-01,  8.6646e-01]]]],
       grad_fn=<ConvolutionBackward0>)
